package ec.edu.ucuenca.registrotramites;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class daf_rrt_tramite implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TRAMITE_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "TRAMITE_ID_SEQ", name = "TRAMITE_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label("Dependencia origen")
   private java.lang.String dependenciaOrigen;

   @org.kie.api.definition.type.Label("Descripcion")
   private java.lang.String descripcion;

   @org.kie.api.definition.type.Label("Es Quipux")
   private java.lang.String esQuipux;

   @org.kie.api.definition.type.Label("Fecha de finalizacion")
   private java.util.Date fechaFinalizacion;

   @org.kie.api.definition.type.Label("Fecha de ingreso")
   private java.util.Date fechaIngresoTramite;

   @org.kie.api.definition.type.Label("Fecha de solicitud")
   private java.util.Date fechaSolicitud;

   @org.kie.api.definition.type.Label("Finalizado")
   private java.lang.String finalizado;

   @org.kie.api.definition.type.Label("Numero de documento")
   private java.lang.String numeroDocumento;

   @org.kie.api.definition.type.Label("Solicitante")
   private java.lang.String solicitante;

   @javax.persistence.OneToMany(fetch = javax.persistence.FetchType.EAGER, cascade = { javax.persistence.CascadeType.ALL })
   @org.kie.api.definition.type.Label("Reasignacion")
   private java.util.List<ec.edu.ucuenca.registrotramites.daf_rrt_reasignacion> reasignacion;

   @org.kie.api.definition.type.Label("Numero Unico de Tramite")
   private java.lang.String numeroUnicoTramite;

   @org.kie.api.definition.type.Label("Documento con el que finaliza")
   private java.lang.String documentoFinaliza;

   @org.kie.api.definition.type.Label(value = "idProceso")
   private java.lang.Long idProceso;

   public daf_rrt_tramite()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getDependenciaOrigen()
   {
      return this.dependenciaOrigen;
   }

   public void setDependenciaOrigen(java.lang.String dependenciaOrigen)
   {
      this.dependenciaOrigen = dependenciaOrigen;
   }

   public java.lang.String getDescripcion()
   {
      return this.descripcion;
   }

   public void setDescripcion(java.lang.String descripcion)
   {
      this.descripcion = descripcion;
   }

   public java.util.Date getFechaFinalizacion()
   {
      return this.fechaFinalizacion;
   }

   public void setFechaFinalizacion(java.util.Date fechaFinalizacion)
   {
      this.fechaFinalizacion = fechaFinalizacion;
   }

   public java.util.Date getFechaIngresoTramite()
   {
      return this.fechaIngresoTramite;
   }

   public void setFechaIngresoTramite(java.util.Date fechaIngresoTramite)
   {
      this.fechaIngresoTramite = fechaIngresoTramite;
   }

   public java.util.Date getFechaSolicitud()
   {
      return this.fechaSolicitud;
   }

   public void setFechaSolicitud(java.util.Date fechaSolicitud)
   {
      this.fechaSolicitud = fechaSolicitud;
   }

   public java.lang.String getNumeroDocumento()
   {
      return this.numeroDocumento;
   }

   public void setNumeroDocumento(java.lang.String numeroDocumento)
   {
      this.numeroDocumento = numeroDocumento;
   }

   public java.lang.String getSolicitante()
   {
      return this.solicitante;
   }

   public void setSolicitante(java.lang.String solicitante)
   {
      this.solicitante = solicitante;
   }

   public java.util.List<ec.edu.ucuenca.registrotramites.daf_rrt_reasignacion> getReasignacion()
   {
      return this.reasignacion;
   }

   public void setReasignacion(
         java.util.List<ec.edu.ucuenca.registrotramites.daf_rrt_reasignacion> reasignacion)
   {
      this.reasignacion = reasignacion;
   }

   public java.lang.String getNumeroUnicoTramite()
   {
      return this.numeroUnicoTramite;
   }

   public void setNumeroUnicoTramite(java.lang.String numeroUnicoTramite)
   {
      this.numeroUnicoTramite = numeroUnicoTramite;
   }

   public java.lang.String getDocumentoFinaliza()
   {
      return this.documentoFinaliza;
   }

   public void setDocumentoFinaliza(java.lang.String documentoFinaliza)
   {
      this.documentoFinaliza = documentoFinaliza;
   }

   public java.lang.String getEsQuipux()
   {
      return this.esQuipux;
   }

   public void setEsQuipux(java.lang.String esQuipux)
   {
      this.esQuipux = esQuipux;
   }

   public java.lang.String getFinalizado()
   {
      return this.finalizado;
   }

   public void setFinalizado(java.lang.String finalizado)
   {
      this.finalizado = finalizado;
   }

   public java.lang.Long getIdProceso()
   {
      return this.idProceso;
   }

   public void setIdProceso(java.lang.Long idProceso)
   {
      this.idProceso = idProceso;
   }

   public daf_rrt_tramite(
         java.lang.Long id,
         java.lang.String dependenciaOrigen,
         java.lang.String descripcion,
         java.lang.String esQuipux,
         java.util.Date fechaFinalizacion,
         java.util.Date fechaIngresoTramite,
         java.util.Date fechaSolicitud,
         java.lang.String finalizado,
         java.lang.String numeroDocumento,
         java.lang.String solicitante,
         java.util.List<ec.edu.ucuenca.registrotramites.daf_rrt_reasignacion> reasignacion,
         java.lang.String numeroUnicoTramite,
         java.lang.String documentoFinaliza, java.lang.Long idProceso)
   {
      this.id = id;
      this.dependenciaOrigen = dependenciaOrigen;
      this.descripcion = descripcion;
      this.esQuipux = esQuipux;
      this.fechaFinalizacion = fechaFinalizacion;
      this.fechaIngresoTramite = fechaIngresoTramite;
      this.fechaSolicitud = fechaSolicitud;
      this.finalizado = finalizado;
      this.numeroDocumento = numeroDocumento;
      this.solicitante = solicitante;
      this.reasignacion = reasignacion;
      this.numeroUnicoTramite = numeroUnicoTramite;
      this.documentoFinaliza = documentoFinaliza;
      this.idProceso = idProceso;
   }

}